name: Build, deploy and restart
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: fifsky/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          user: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          command: |
            cd ~/ssemmi-api
            ls
            ./build_and_deploy.sh
            echo 'Deployment successful to digital ocean'
